### ISSUE TITLE
r2g init yields error

### ISSUE THREAD

**Issue by mister-cholo** [ORESoftware/r2g#13]
I am seeing this after running: `r2g init` in a project:

```console
r2g: events.js:167
r2g: throw er; // Unhandled 'error' event
r2g: ^
r2g: 
r2g: Error: ENOENT: no such file or directory, open '/Users/Olegzandr/.nvm/versions/node/v10.6.0/lib/node_modules/@oresoftware/r2g/assets/contents/Dockerfile.r2g.original'
r2g: Emitted 'error' event at:
r2g: at fs.open (internal/fs/streams.js:100:12)
r2g: at FSReqWrap.oncomplete (fs.js:145:20)
```

**Comment by ORESoftware** [comment]
all good now
